version: "3.8"

services:

  frontend:
    container_name: frontend
    image: node:12.16.1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && node server.js"

